# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        version: ["v3.11", "v3.12", "v3.13"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        git fetch --deepen 50
        uv venv --python=${{ matrix.version }}
        uv pip install pytest
        uv pip install jupyter nbconvert
        uv sync --all-extras --dev
    - name: Test with pytest
      run: |
        uv run pytest
